{
  "4 Ways to handle mapDispatchToProps": {
    "prefix": "r_mapdispatchtoprops",
    "body": [
      "// 4 ways to handle mapDispatchToProps",
      "​",
      "//1. ignore it",
      "​",
      "//in component",
      "this.Props.dispatch(loadCourses());",
      "​",
      "//2. Manually wrap in dispatch",
      "​",
      "function mapDispatchToProps(dispatch) {",
      "  return {",
      "    loadCourses: () =>  { dispatch(loadCourses()) },",
      "    createCourses: course => dispatch(createCourse(course))",
      "  }",
      "}",
      "//in component",
      "this.props.loadCourses",
      "​",
      "​",
      "//3. Use bindActionCreators",
      "​",
      "function mapDispatchToProps(dispatch) {",
      "  return {",
      "    actions: bindActionCreators(action, dispatch)",
      "  }",
      "}",
      "//in component",
      "this.props.actions.loadCourses()",
      "​",
      "//4 return object",
      "​",
      "const mapDispatchToProps = {",
      "  incrementCounter",
      "};",
      "​",
      "//in Component",
      "this.props.loadCourses();"
    ],
    "description": "4 Ways to handle mapDispatchToProps"
  }
}